server:
  port: 8080

spring:
  data:
    redis:
      port: 8888


  datasource:
    url: jdbc:mariadb://localhost:3306/testDB  # MySQL ????? ??
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
